spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/volunteer?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:rootpassword}
    hikari:
      idleTimeout: 60000
      maxLifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    dev.langchain4j: INFO
    com.itheima.consultant: DEBUG
  file:
    name: logs/app.log
  config: classpath:logback-spring.xml

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${LANGCHAIN4J_OPENAI_CHATMODEL_APIKEY}
      model-name: qwen-plus
      log-requests: false
      log-responses: false
      timeout: 60s
      max-retries: 3
      
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${LANGCHAIN4J_OPENAI_CHATMODEL_APIKEY}
      model-name: qwen-plus
      log-requests: false
      log-responses: false
      timeout: 60s
      
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${LANGCHAIN4J_OPENAI_EMBEDDINGMODEL_APIKEY}
      model-name: text-embedding-v3
      log-requests: false
      log-responses: false
      max-segments-per-batch: 10
      
  community:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

# 应用监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
